"""feat: xxx

Revision ID: 0593b88bbfa6
Revises: c325bbe8ad3b
Create Date: 2025-10-13 23:24:30.106960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0593b88bbfa6'
down_revision: Union[str, Sequence[str], None] = 'c325bbe8ad3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
