"""init schema

Revision ID: 2fb008b62fb7
Revises: 
Create Date: 2025-10-13 22:09:23.222530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2fb008b62fb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('trade_details')
    op.drop_index(op.f('uq_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_table('trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('trd_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('datetime', mysql.TIMESTAMP(), nullable=False),
    sa.Column('emp_cd', mysql.CHAR(length=10), nullable=False),
    sa.Column('store_cd', mysql.CHAR(length=5), nullable=False),
    sa.Column('pos_no', mysql.CHAR(length=3), nullable=False),
    sa.Column('total_amt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ttl_amt_ex_tax', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trd_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('prd_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.CHAR(length=13), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('prd_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_products_code'), 'products', ['code'], unique=True)
    op.create_table('trade_details',
    sa.Column('trd_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dtl_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prd_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('prd_code', mysql.CHAR(length=13), nullable=False),
    sa.Column('prd_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('prd_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tax_cd', mysql.CHAR(length=2), server_default=sa.text("'10'"), nullable=False),
    sa.ForeignKeyConstraint(['prd_id'], ['products.prd_id'], name=op.f('fk_trade_details_prd_id_products')),
    sa.ForeignKeyConstraint(['trd_id'], ['trades.trd_id'], name=op.f('fk_trade_details_trd_id_trades')),
    sa.PrimaryKeyConstraint('trd_id', 'dtl_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
