"""init schema

Revision ID: c325bbe8ad3b
Revises: 2fb008b62fb7
Create Date: 2025-10-13 23:19:06.326615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c325bbe8ad3b'
down_revision: Union[str, Sequence[str], None] = '2fb008b62fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
